config/routes.rb
Rails.application.routes.draw do
  
  resources :movies do
  	resources :reviews, except: [:show, :index]
  end
  devise_for :users
  root to: "movies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	validates :name,  presence: true
  	# validates :year, presence: true
  	validates :rating, presence: true
  	validates :year, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
  	# validates :rating, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
  	# validates_inclusion_of :rating, message: "Only Rate 1 to 5 without sign"

  	belongs_to :user
	has_many :reviews
	has_attached_file :image, styles: { medium: "400x400>", thumb: "300x200>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	# validates :Rate, length: { in: 1..5 }
  	validates :comment, presence: true

	belongs_to :movie
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show ]

  def index
  @q = Movie.ransack(params[:q])
  @movies = @q.result(distinct: true)
end

  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2) 
    end 
  end

  
  def new
    @movie = current_user.movies.build
  end

  
  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_movie
      @movie = Movie.find(params[:id])
    end

    
    def movie_params
      params.require(:movie).permit(:name, :year, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!
  
  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id
    
      if @review.save
        redirect_to @movie
      else
        render 'new'
      end
  end

 
  def update
       @review.update(review_params)
  end

  
  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    
    def set_review
      @review = Review.find(params[:id])
    end
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<sapn class="sr-only">Toggle navigation</sapn>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Movies", root_path, class: "navbar-brand"%>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
					<li><%= link_to "New Movie", new_movie_path, class: "active"%></li>
					<li><%= link_to "Account", edit_user_registration_path, class: "pull-right" %></li>
					<li><%= link_to "SIgn Out", destroy_user_session_path, :method => :delete,  class: "pull-right" %></li>
				<% else %>
					<li><%= link_to "SIgn Up", new_user_registration_path,  class: "active"%></li>
					<li> <%= link_to "SIgn In", new_user_session_path, class: "active"%></li>
					
				<% end %>
			</ul>
			
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header'%>
  	<div class="container">
  	<% flash.each do |name, msg|%>
  		<%= content_tag(:div, msg, class: "alert alert-info")%>
		<% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
      <%= form_with(model: movie, local: true) do |form| %>
        <% if movie.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

            <ul>
            <% movie.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%#= form.label :Image %>
          <%#= form.file_field :image %>
        </div>
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, id: :movie_name , class: "form-control"%>
        </div>

        <div class="field">
          <%= form.label :year %>
          <%#= form.number_field :year, in: 1...10 , class: "form-control"%>
          <%= form.number_field :year, id: :movie_year, value: "2018", class: "form-control" %>
        </div>
        <div class="field">
          <%= form.label :Rating %>
          <%= form.number_field :rating, in: 1...6, value: "1" ,class: "form-control" %>
        </div>
        
      <br>
        <div class="form-action">
          <%= form.submit class: "btn btn-success"  %>
        </div>
      <% end %>
    <!-- number_field_tag 'quantity', nil, in: 1...10 -->

app/views/movies/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
		<h1>Editing Movie</h1>
		
      <%= form_with(model: @movie, local: true) do |form| %>
        <% if @movie.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

            <ul>
            <% movie.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%#= form.label :Image %>
          <%#= form.file_field :image %>
        </div>
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, id: :movie_name , class: "form-control"%>
        </div>

        <div class="field">
          <%= form.label :year %>
          <%#= form.number_field :year, in: 1...10 , class: "form-control"%>
          <%= form.number_field :year, id: :movie_year, class: "form-control" %>
        </div>
        <div class="field">
          <%= form.label :Rating %>
          <%= form.number_field :rating, in: 1...6, class: "form-control" %>
        </div>
        
      <br>
        <div class="form-action">
          <%= form.submit class: "btn btn-success"  %>
        </div>
      <% end %>
    <!-- number_field_tag 'quantity', nil, in: 1...10 -->
		<br><br>
		<%= link_to 'Show', @movie %> |
		<%= link_to 'Back', movies_path %>
		</div>
	</div>
</div>

app/views/movies/index.html.erb
    
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h2 style = "font-size: 40px;">Welcome to Movie Review</h2>
    <p style= "color: #6d6868; font-size:18px;">Did you really love or hate that blockbuster movie and you want people to know what you thought? Now you can rant or rave on websites and apps like Rotten Tomatoes and Family Movie Reviews. You can also discover new movies, read current movie reviews, or find movie ratings for kids..</p>
    <%= link_to "Sign Up for Review", new_user_registration_path, class: "btn btn-primary btn-lg"%>
  </div>
<% end %>
<div class="row"> 
    <div style="margin-right: 18px;">
      <%= search_form_for (@q) do |f|  %>
          <%= f.search_field :name_cont, placeholder:"Search Movie...", id: "sbar", class: "pull-right" %>  
      <% end %>
     </div>
    </div>
    <br>

<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <%= link_to movie do %>
      <div class="thumbnail">
        <center> <h3> <b><%= movie.name%> </b> </h3> </center>  
        <center><h5> Year Of Release: <%= movie.year%> </h5> </center> 
        <br>
        
        <%#= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      <%end%>
      </div>

    </div>
    <% end %>
</div>

app/views/movies/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
	<h1>New Movie</h1>
	<%= render 'form', movie: @movie %>
	<br>
	<%= link_to 'Back', movies_path %>
		</div>
	</div>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">

				<%#= image_tag @movie.image.url(:medium), class:"show-image" %>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td><strong>Average Rating:</strong> </td>
								<td><div class="star-rating" data-score= <%= @avg_review%></div></td>
								<td><em><%= "#{@reviews.length} reviews"%></em></td>
							</tr>
							<tr>
								<td> <strong>Name:</strong> </td>
								<td> <%= @movie.name %> </td>
							</tr>
							<tr>
								<td> <strong>Year Of Release: </strong> </td>
								<td> <%= @movie.year %> </td>
							</tr>
							<tr>
								<td> <strong>Rating By Us: </strong> </td>
								<td> <div class="star-rating" data-score= <%= @movie.rating %> </div>  </td>
							</tr>
							
						</tbody>
					</table>
					
				</div>
			</div>
			<div class="col-md-7 col-md-offset-1">
				<h1 class="review_title"><%= @movie.name %></h1>
				<p><%= @movie.year %></p>

				<% if @reviews.blank?%>
					<h3>No reviews just yet, would you like to add first!</h3>
					<%= link_to "Give First Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
				<% else %>
					<% @reviews.each do |review| %>
						<div class="reviews">
						 	<div class="star-rating" data-score= <%= review.rating %> ></div>	 
							<p> <%= review.comment %> </p>
							<hr>
						</div>
						<%end%>
				<% end %>
				<%= link_to "Leave a review Here", new_movie_review_path(@movie), class: "btn btn-success" %>
			</div>
		</div>
	</div>
</div>
<% if user_signed_in? %>
	<% if @movie.user_id == current_user.id%>
	<%= link_to 'Delete', movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' } %>| 
	<%= link_to 'Edit', edit_movie_path(@movie) %> 
| <% end %>
<%end%>
<%= link_to 'Back', movies_path %>


<script>
	$('.star-rating').raty({
		path: '/assets',
		readOnly: true,
		score: function(){
			return $(this).attr('data-score')
		}
	});
</script>

app/views/reviews/_form.html.erb
<div class="container">
   <%= form_with(model: [@movie, review], local: true) do |form| %>
    <% if review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
       <%= form.label :Rate %> <br>
     <div id="star-rating"></div>
    </div>
    <br>
    <div class="field">
      <%= form.label :comment %> <br>
      <%= form.text_area :comment, id: :review_comment %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">


<h1>New Review</h1>

<%= render 'form', review: @review %>
<br>

<%= link_to 'Back', root_path %>

	</div>
</div>
</div>

app/views/reviews/show.html.erb
<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>
<p>
	<strong>User:</strong>
  <%= @review.user.email %>		
</p>
<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>